/**
 * Extracts the osCommerce schema (and the pure lookup data) from a phpMyAdmin
 * dump of the legacy shop database.
 *
 * The production dump carries real customer data and must never enter the repo.
 * This script distils the two parts that are safe to commit and that make the
 * project reproducible without it:
 *
 *   database/schema/oscommerce.sql   DDL only — CREATE TABLE + the trailing
 *                                    ALTER TABLE (keys, AUTO_INCREMENT) blocks
 *   database/seed/reference.sql      rows of the lookup tables whose ids the
 *                                    application hard-codes (country ids, tax
 *                                    zones/rates, order status names)
 *
 * Usage (from the repo root):
 *   node database/extract-schema.mjs old/kooperative_db2.sql
 *
 * Re-run it when the legacy schema changes; the output is meant to be committed.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Every table the application reads or writes, plus the lookups they join to.
 *
 * Reads are visible as literal SQL, but writes go through the dbInsert/dbUpdate
 * helpers with the table as a parameter — grep for both when extending this:
 *
 *   grep -rnE "\\b(FROM|JOIN|INTO|UPDATE)\\s+\`?[a-z_]+" app/server
 *   grep -rnA3 -E "db(Insert|Update|UpdateExpr|Delete)\\(" app/server
 */
const SCHEMA_TABLES = [
  'address_book',
  'banktransfer_iban',
  'categories',
  'categories_description',
  'countries',
  'customers',
  'customers_info',
  'geo_zones',
  'orders',
  'orders_products',
  'orders_status',
  'orders_status_history',
  'orders_total',
  'products',
  'products_description',
  'products_to_categories',
  'reviews',
  'tax_class',
  'tax_rates',
  'zones_to_geo_zones',
]

/**
 * Lookup tables copied verbatim. These hold no personal data, but their ids are
 * referenced from the code (COUNTRY_IDS, checkoutOptions.taxClassId,
 * ORDER_STATUS_FLOW), so invented values would make the seed lie.
 */
const REFERENCE_TABLES = ['countries', 'geo_zones', 'orders_status', 'tax_class', 'tax_rates', 'zones_to_geo_zones']

const dumpPath = process.argv[2]
if (!dumpPath) {
  console.error('usage: node database/extract-schema.mjs <dump.sql>')
  process.exit(2)
}

const sql = readFileSync(dumpPath, 'utf8')

/** Grab a `<keyword> \`table\` ... ;` statement, allowing several per table. */
function statements(keyword, table) {
  const found = []
  const start = new RegExp(`^${keyword} \`${table}\`[\\s(]`, 'm')
  let rest = sql
  for (;;) {
    const m = start.exec(rest)
    if (!m) break
    const from = m.index
    const end = rest.indexOf(';\n', from)
    if (end === -1) break
    found.push(rest.slice(from, end + 1))
    rest = rest.slice(end + 1)
  }
  return found
}

const missing = []
const schema = [
  '-- osCommerce legacy schema — DDL only, generated by database/extract-schema.mjs.',
  '-- Do not edit by hand; re-run the extractor against the production dump instead.',
  '',
  'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";',
  'SET time_zone = "+00:00";',
  '',
]

for (const table of SCHEMA_TABLES) {
  const create = statements('CREATE TABLE', table)
  if (create.length === 0) {
    missing.push(table)
    continue
  }
  schema.push(`DROP TABLE IF EXISTS \`${table}\`;`, create[0], '')
}

// The keys and AUTO_INCREMENT counters live in ALTER TABLE blocks at the end of
// a phpMyAdmin dump, so they have to be appended after every table exists.
for (const table of SCHEMA_TABLES) {
  for (const alter of statements('ALTER TABLE', table)) {
    // AUTO_INCREMENT counters are derived from the production row count — reset
    // them so a fresh database starts at 1 and ids stay predictable in tests.
    schema.push(alter.replace(/AUTO_INCREMENT=\d+/g, 'AUTO_INCREMENT=1'), '')
  }
}

const reference = [
  '-- Lookup data from the legacy shop: countries, tax zones/rates, order status.',
  '-- No personal data. Generated by database/extract-schema.mjs.',
  '',
]

for (const table of REFERENCE_TABLES) {
  const inserts = statements('INSERT INTO', table)
  if (inserts.length === 0) {
    missing.push(`${table} (data)`)
    continue
  }
  reference.push(`TRUNCATE TABLE \`${table}\`;`, ...inserts, '')
}

if (missing.length > 0) {
  console.error(`missing in dump: ${missing.join(', ')}`)
  process.exit(1)
}

mkdirSync(join(__dirname, 'schema'), { recursive: true })
mkdirSync(join(__dirname, 'seed'), { recursive: true })
writeFileSync(join(__dirname, 'schema', 'oscommerce.sql'), schema.join('\n'))
writeFileSync(join(__dirname, 'seed', 'reference.sql'), reference.join('\n'))

console.log(`schema/oscommerce.sql  ${SCHEMA_TABLES.length} tables`)
console.log(`seed/reference.sql     ${REFERENCE_TABLES.length} lookup tables`)
